/**
 * Type definitions for the canonical counts.json file at the repo root.
 *
 * counts.json is the single source of truth for all counter numbers
 * (commands, agents, skills, rules, domain subtotals) referenced
 * across TS components, Markdown docs and CI configuration.
 *
 * It is generated by website/scripts/generate-counts.ts on every
 * `npm run build`. CI fails if the committed counts.json drifts from
 * what the generator produces.
 */

export interface Counts {
  /** Total .md files under .claude/commands/ (excluding README.md) */
  commands: number;

  /** Total .md files under .claude/agents/ (excluding README.md) */
  agents: number;

  /** Total SKILL.md files under .claude/skills/ */
  skills: number;

  /**
   * What a DEFAULT (opt-in) install ships: the full catalog minus the
   * horizontal module-owned items (biz/legal/growth bundles). The
   * commands/agents/skills above are the foundation catalog (core + modules).
   * See specs/horizontal-pure-modules/.
   */
  core: {
    commands: number;
    agents: number;
    skills: number;
  };

  /** Total .md files under .claude/rules/ (excluding README.md) */
  rules: number;

  /**
   * Per-domain command subtotals. Keys are lowercase domain folder names
   * (work, dev, qa, ops, doc, biz, growth, data, legal). New domains are
   * picked up automatically — consumers must handle missing keys.
   */
  byDomain: Record<string, number>;

  /** Total *.json manifests under .claude/presets/ (top level, excludes community/) */
  presets: number;

  /**
   * Total vendor entries listed under the "Recommended vendor skills
   * (by domain)" section of docs/recipes/recommended-vendor-skills.md.
   * Excludes the "Stack-specific" and "Vendors evaluated and NOT
   * recommended" subsections.
   */
  vendorSkillsValidated: number;

  /**
   * Total marketplace-audit pilot specs under specs/marketplace-audit/
   * matching the `*-pilot-*.md` filename pattern. Excludes spec.md and
   * other non-pilot documents.
   */
  marketplaceAuditPilots: number;
}
