#!/usr/bin/env bash
# =============================================================================
# inventory.sh — generates inventory.json with files-per-tier list
# =============================================================================
# Tier 1: README.md, CLAUDE.md, docs/guides/*.md, docs/reference/*.md,
#         .claude/rules/*.md
# Tier 2: .claude/agents/*.md, .claude/commands/**/*.md
# Tier 3: .claude/skills/**/* (excluding auto-generated), scripts/hooks/*.sh
# Tier 4: website/docs/{intro,guides,reference,concepts,workflow,tutorials,examples}/**/*.md
#         NOTE: website/docs/{commands,agents,skills,rules}/ are auto-generated
#               from .claude/* and will be regenerated after T2+T3 merge.
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
OUTPUT_FILE="$REPO_ROOT/specs/migration-fr-en/inventory.json"

cd "$REPO_ROOT"

# -----------------------------------------------------------------------------
# Tier 1: vitrine + rules (~42 files, ~50k words)
# -----------------------------------------------------------------------------
tier1_files=()
[[ -f README.md ]] && tier1_files+=("README.md")
[[ -f CLAUDE.md ]] && tier1_files+=("CLAUDE.md")
while IFS= read -r f; do tier1_files+=("$f"); done < <(find docs/guides -type f -name "*.md" 2>/dev/null | sort)
while IFS= read -r f; do tier1_files+=("$f"); done < <(find docs/reference -type f -name "*.md" 2>/dev/null | sort)
while IFS= read -r f; do tier1_files+=("$f"); done < <(find .claude/rules -type f -name "*.md" 2>/dev/null | sort)

# -----------------------------------------------------------------------------
# Tier 2: agents + commands (194 files, ~80k words)
# -----------------------------------------------------------------------------
tier2_files=()
while IFS= read -r f; do tier2_files+=("$f"); done < <(find .claude/agents -type f -name "*.md" 2>/dev/null | sort)
while IFS= read -r f; do tier2_files+=("$f"); done < <(find .claude/commands -type f -name "*.md" 2>/dev/null | sort)

# -----------------------------------------------------------------------------
# Tier 3: skills + hooks (~60k words)
# -----------------------------------------------------------------------------
tier3_files=()
while IFS= read -r f; do tier3_files+=("$f"); done < <(find .claude/skills -type f \( -name "*.md" -o -name "SKILL.md" \) 2>/dev/null | sort)
while IFS= read -r f; do tier3_files+=("$f"); done < <(find scripts/hooks -type f -name "*.sh" 2>/dev/null | sort)

# -----------------------------------------------------------------------------
# Tier 4: website hand-maintained docs (~77 files, ~111k words)
# Excludes auto-generated dirs (commands, agents, skills, rules) which
# will be regenerated by `cd website && npm run generate` after T2+T3 merge.
# -----------------------------------------------------------------------------
tier4_files=()
for dir in intro guides reference concepts workflow tutorials examples; do
    while IFS= read -r f; do tier4_files+=("$f"); done < <(find "website/docs/$dir" -type f \( -name "*.md" -o -name "*.mdx" \) 2>/dev/null | sort)
done

# -----------------------------------------------------------------------------
# Word counts per tier
# -----------------------------------------------------------------------------
count_words() {
    local files=("$@")
    if [[ ${#files[@]} -eq 0 ]]; then echo 0; return; fi
    wc -w "${files[@]}" 2>/dev/null | tail -1 | awk '{print $1}'
}

t1_words=$(count_words "${tier1_files[@]}")
t2_words=$(count_words "${tier2_files[@]}")
t3_words=$(count_words "${tier3_files[@]}")
t4_words=$(count_words "${tier4_files[@]}")
total_words=$((t1_words + t2_words + t3_words + t4_words))
total_files=$((${#tier1_files[@]} + ${#tier2_files[@]} + ${#tier3_files[@]} + ${#tier4_files[@]}))

# -----------------------------------------------------------------------------
# Generate JSON
# -----------------------------------------------------------------------------
generated_at="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

json_array() {
    local files=("$@")
    if [[ ${#files[@]} -eq 0 ]]; then echo "[]"; return; fi
    printf '['
    local first=true
    for f in "${files[@]}"; do
        if $first; then first=false; else printf ','; fi
        printf '\n      "%s"' "$f"
    done
    printf '\n    ]'
}

{
    echo "{"
    echo "  \"generated_at\": \"$generated_at\","
    echo "  \"summary\": {"
    echo "    \"total_files\": $total_files,"
    echo "    \"total_words\": $total_words"
    echo "  },"
    echo "  \"tiers\": {"
    echo "    \"1\": {"
    echo "      \"label\": \"Showcase + rules (P1, blocking)\","
    echo "      \"files_count\": ${#tier1_files[@]},"
    echo "      \"words\": $t1_words,"
    echo "      \"files\": $(json_array "${tier1_files[@]}")"
    echo "    },"
    echo "    \"2\": {"
    echo "      \"label\": \"Agents and commands\","
    echo "      \"files_count\": ${#tier2_files[@]},"
    echo "      \"words\": $t2_words,"
    echo "      \"files\": $(json_array "${tier2_files[@]}")"
    echo "    },"
    echo "    \"3\": {"
    echo "      \"label\": \"Skills and hooks\","
    echo "      \"files_count\": ${#tier3_files[@]},"
    echo "      \"words\": $t3_words,"
    echo "      \"files\": $(json_array "${tier3_files[@]}")"
    echo "    },"
    echo "    \"4\": {"
    echo "      \"label\": \"Website hand-maintained docs (auto-generated dirs excluded)\","
    echo "      \"files_count\": ${#tier4_files[@]},"
    echo "      \"words\": $t4_words,"
    echo "      \"files\": $(json_array "${tier4_files[@]}")"
    echo "    }"
    echo "  },"
    echo "  \"notes\": ["
    echo "    \"website/docs/{commands,agents,skills,rules}/ are auto-generated from .claude/* via website/scripts/generate-*.ts and excluded from Tier 4.\","
    echo "    \"After merging Tier 2 and Tier 3, run 'cd website && npm run generate' to regenerate the auto-generated docs in EN.\""
    echo "  ]"
    echo "}"
} > "$OUTPUT_FILE"

echo "[inventory] Generated $OUTPUT_FILE"
echo "[inventory] Tier 1: ${#tier1_files[@]} files, $t1_words words"
echo "[inventory] Tier 2: ${#tier2_files[@]} files, $t2_words words"
echo "[inventory] Tier 3: ${#tier3_files[@]} files, $t3_words words"
echo "[inventory] Tier 4: ${#tier4_files[@]} files, $t4_words words"
echo "[inventory] TOTAL : $total_files files, $total_words words"
