#!/usr/bin/env bash
# =============================================================================
# gen-pristine-hashes.sh — record the sha256 of every version of the managed
# scripts the foundation ever shipped, so `update` can tell an UNMODIFIED copy
# of an older release from a customised one.
#
# Why: both simply differ from today's copy. update skipped both without
# --force, and --force overwrote real customisations along with them — so even
# `update --hook-scripts` left a v5.3.0 install's security libraries on their
# v5.3.0 rules (measured 2026-09-15). Installs are `git clone --depth 1`: the
# history is not there at update time, so the answer is computed here, from the
# full history, and shipped as scripts/lib/pristine-hashes.txt.
#
# Managed set: scripts/hooks/*.sh and scripts/substance-check.sh (the detector
# update refreshes alongside the hooks).
#
# Sources: every blob those paths held in any commit reachable from HEAD, plus
# the INDEX (so the pre-commit hook records a version before it is committed).
#
# Modes:
#   (default)  write the table
#   --check    READ-ONLY: exit 1 if any shipped version is missing from the
#              committed table. Extra entries are tolerated: a squash merge
#              drops the intermediate commits a branch recorded, and an entry
#              for foundation-authored content is harmless.
#
# Exit 0 ok · 1 --check found missing versions · 2 shallow clone / usage error.
#
# Test seam: PRISTINE_ROOT (repo root; default: this script's parent dir).
# macOS bash 3.2 compatible.
# =============================================================================

set -euo pipefail

ROOT="${PRISTINE_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
TABLE="$ROOT/scripts/lib/pristine-hashes.txt"
MODE="${1:-write}"

case "$MODE" in
    write|--check) ;;
    *) echo "usage: $(basename "$0") [--check]" >&2; exit 2 ;;
esac

if [ "$(git -C "$ROOT" rev-parse --is-shallow-repository)" != "false" ]; then
    echo "[pristine-hashes] shallow clone: the history the table is derived from is not here. Run 'git fetch --unshallow' first." >&2
    exit 2
fi

sha256_stdin() {
    if command -v sha256sum >/dev/null 2>&1; then sha256sum | cut -d' ' -f1
    else shasum -a 256 | cut -d' ' -f1
    fi
}

is_managed() {
    case "$1" in
        scripts/substance-check.sh) return 0 ;;
        scripts/hooks/*/*) return 1 ;;
        scripts/hooks/*.sh) return 0 ;;
    esac
    return 1
}

# "<blob> <path>" for every version of a managed path: the post-image of each
# change in history (renames split into delete + add, so a moved file keeps its
# versions under both paths; -m and --full-history so content that only a merge
# commit introduced, like a resolved conflict, is seen), then the index.
blob_paths() {
    if git -C "$ROOT" rev-parse -q --verify HEAD >/dev/null 2>&1; then
        git -C "$ROOT" log -m --full-history --format= --raw --no-abbrev --no-renames HEAD -- scripts/hooks scripts/substance-check.sh \
            | awk -F'\t' '{ split($1, m, " "); if (m[4] !~ /^0+$/) print m[4] " " $2 }'
    fi
    git -C "$ROOT" ls-files -s -- scripts/hooks scripts/substance-check.sh \
        | awk -F'\t' '{ split($1, m, " "); print m[2] " " $2 }'
}

generate() {
    local blob path
    blob_paths | sort -u | while read -r blob path; do
        is_managed "$path" || continue
        printf '%s %s\n' "$(git -C "$ROOT" cat-file blob "$blob" | sha256_stdin)" "$path"
    done | LC_ALL=C sort -u
}

HEADER="# Generated by scripts/gen-pristine-hashes.sh - do not edit.
# sha256 of every version of scripts/hooks/*.sh and scripts/substance-check.sh
# the foundation shipped. update replaces a copy whose hash is listed for its
# path: it is an unmodified foundation copy, not a customisation."

if [ "$MODE" = "--check" ]; then
    if [ ! -f "$TABLE" ]; then
        echo "[pristine-hashes] $TABLE is missing. Run scripts/gen-pristine-hashes.sh." >&2
        exit 1
    fi
    missing=$(generate | LC_ALL=C comm -23 - <(grep -v '^#' "$TABLE" | LC_ALL=C sort -u))
    if [ -n "$missing" ]; then
        echo "[pristine-hashes] shipped versions missing from the table - run scripts/gen-pristine-hashes.sh:" >&2
        printf '%s\n' "$missing" >&2
        exit 1
    fi
    exit 0
fi

mkdir -p "$(dirname "$TABLE")"
{ printf '%s\n' "$HEADER"; generate; } > "$TABLE.tmp"
mv "$TABLE.tmp" "$TABLE"
