import React from 'react';
import counts from '../../../counts.json';

interface StatItem {
  number: string | number;
  label: string;
}

export interface StatsProps {
  items: StatItem[];
}

export default function Stats({ items }: StatsProps): JSX.Element {
  return (
    <div className="stats-grid">
      {items.map((item) => (
        <div key={item.label} className="stat-card">
          <div className="stat-card__number">{item.number}</div>
          <div className="stat-card__label">{item.label}</div>
        </div>
      ))}
    </div>
  );
}

// Pre-defined stats for claude-socle, sourced from counts.json
// (the single source of truth, regenerated by `npm run generate`).
export const SOCLE_STATS: StatItem[] = [
  { number: counts.commands, label: 'Commands' },
  { number: counts.agents, label: 'Agents' },
  { number: counts.skills, label: 'Skills' },
  { number: counts.rules, label: 'Rules' },
];
