import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // Introduction sidebar
  introSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      collapsed: false,
      items: [
        'intro/index',
        'intro/quick-start',
        'intro/architecture',
        'intro/installation',
      ],
    },
  ],

  // Concepts Claude Code sidebar
  conceptsSidebar: [
    {
      type: 'category',
      label: 'Concepts Claude Code',
      collapsed: false,
      link: {
        type: 'doc',
        id: 'concepts/index',
      },
      items: [
        'concepts/commands',
        'concepts/agents',
        'concepts/skills',
        'concepts/rules',
        'concepts/hooks',
        'concepts/mcp-servers',
        'concepts/output-styles',
      ],
    },
  ],

  // Workflow sidebar
  workflowSidebar: [
    {
      type: 'category',
      label: 'Workflows',
      collapsed: false,
      items: [
        'workflow/index',
        'workflow/explore-plan-code-commit',
        'workflow/feature',
        'workflow/bugfix',
        'workflow/release',
        'workflow/launch',
        'workflow/tdd',
        'workflow/choosing-workflow',
      ],
    },
  ],

  // Commands sidebar - organized by domain
  commandsSidebar: [
    {
      type: 'category',
      label: 'Commands',
      collapsed: false,
      link: {
        type: 'doc',
        id: 'commands/index',
      },
      items: [
        {
          type: 'category',
          label: 'WORK (10)',
          collapsed: true,
          link: {
            type: 'doc',
            id: 'commands/work/index',
          },
          items: [
            {type: 'autogenerated', dirName: 'commands/work'},
          ],
        },
        {
          type: 'category',
          label: 'DEV (16)',
          collapsed: true,
          link: {
            type: 'doc',
            id: 'commands/dev/index',
          },
          items: [
            {type: 'autogenerated', dirName: 'commands/dev'},
          ],
        },
        {
          type: 'category',
          label: 'QA (11)',
          collapsed: true,
          link: {
            type: 'doc',
            id: 'commands/qa/index',
          },
          items: [
            {type: 'autogenerated', dirName: 'commands/qa'},
          ],
        },
        {
          type: 'category',
          label: 'OPS (24)',
          collapsed: true,
          link: {
            type: 'doc',
            id: 'commands/ops/index',
          },
          items: [
            {type: 'autogenerated', dirName: 'commands/ops'},
          ],
        },
        {
          type: 'category',
          label: 'DOC (9)',
          collapsed: true,
          link: {
            type: 'doc',
            id: 'commands/doc/index',
          },
          items: [
            {type: 'autogenerated', dirName: 'commands/doc'},
          ],
        },
        {
          type: 'category',
          label: 'BIZ (11)',
          collapsed: true,
          link: {
            type: 'doc',
            id: 'commands/biz/index',
          },
          items: [
            {type: 'autogenerated', dirName: 'commands/biz'},
          ],
        },
        {
          type: 'category',
          label: 'GROWTH (9)',
          collapsed: true,
          link: {
            type: 'doc',
            id: 'commands/growth/index',
          },
          items: [
            {type: 'autogenerated', dirName: 'commands/growth'},
          ],
        },
        {
          type: 'category',
          label: 'DATA (3)',
          collapsed: true,
          link: {
            type: 'doc',
            id: 'commands/data/index',
          },
          items: [
            {type: 'autogenerated', dirName: 'commands/data'},
          ],
        },
        {
          type: 'category',
          label: 'LEGAL (5)',
          collapsed: true,
          link: {
            type: 'doc',
            id: 'commands/legal/index',
          },
          items: [
            {type: 'autogenerated', dirName: 'commands/legal'},
          ],
        },
        'commands/assistant',
      ],
    },
  ],

  // Agents sidebar
  agentsSidebar: [
    {
      type: 'category',
      label: 'Agents',
      collapsed: false,
      link: {
        type: 'doc',
        id: 'agents/index',
      },
      items: [
        {type: 'autogenerated', dirName: 'agents'},
      ],
    },
  ],

  // Skills sidebar
  skillsSidebar: [
    {
      type: 'category',
      label: 'Skills',
      collapsed: false,
      link: {
        type: 'doc',
        id: 'skills/index',
      },
      items: [
        {type: 'autogenerated', dirName: 'skills'},
      ],
    },
  ],

  // Rules sidebar
  rulesSidebar: [
    {
      type: 'category',
      label: 'Rules',
      collapsed: false,
      link: {
        type: 'doc',
        id: 'rules/index',
      },
      items: [
        {type: 'autogenerated', dirName: 'rules'},
      ],
    },
  ],

  // Guides sidebar
  guidesSidebar: [
    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      link: {
        type: 'doc',
        id: 'guides/index',
      },
      items: [
        'guides/web-development',
        'guides/mobile-development',
        'guides/api-development',
        'guides/data-engineering',
        'guides/startup',
      ],
    },
  ],

  // Reference sidebar
  referenceSidebar: [
    {
      type: 'category',
      label: 'Référence',
      collapsed: false,
      link: {
        type: 'doc',
        id: 'reference/index',
      },
      items: [
        'reference/commands-matrix',
        'reference/agents-matrix',
        'reference/cheatsheet',
      ],
    },
  ],
};

export default sidebars;
