import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // Introduction sidebar
  introSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      collapsed: false,
      items: [
        'intro/index',
        'intro/quick-start',
        'intro/architecture',
        'intro/installation',
      ],
    },
  ],

  // Concepts Claude Code sidebar
  conceptsSidebar: [
    {
      type: 'category',
      label: 'Concepts Claude Code',
      collapsed: false,
      link: {
        type: 'doc',
        id: 'concepts/index',
      },
      items: [
        'concepts/orchestrator',
        'concepts/commands',
        'concepts/agents',
        'concepts/skills',
        'concepts/rules',
        'concepts/hooks',
        'concepts/mcp-servers',
        'concepts/output-styles',
        'concepts/advanced-features',
      ],
    },
  ],

  // Workflow sidebar
  workflowSidebar: [
    {
      type: 'category',
      label: 'Workflows',
      collapsed: false,
      items: [
        'workflow/index',
        'workflow/explore-plan-code-commit',
        'workflow/feature',
        'workflow/bugfix',
        'workflow/release',
        'workflow/launch',
        'workflow/tdd',
        'workflow/choosing-workflow',
      ],
    },
  ],

  // Commands sidebar - organized by domain
  commandsSidebar: [
    {
      type: 'category',
      label: 'Commands',
      collapsed: false,
      link: {
        type: 'doc',
        id: 'commands/index',
      },
      items: [
        {
          type: 'category',
          label: 'WORK (12)',
          collapsed: true,
          link: {
            type: 'doc',
            id: 'commands/work/index',
          },
          items: [
            {type: 'autogenerated', dirName: 'commands/work'},
          ],
        },
        {
          type: 'category',
          label: 'DEV (23)',
          collapsed: true,
          link: {
            type: 'doc',
            id: 'commands/dev/index',
          },
          items: [
            {type: 'autogenerated', dirName: 'commands/dev'},
          ],
        },
        {
          type: 'category',
          label: 'QA (15)',
          collapsed: true,
          link: {
            type: 'doc',
            id: 'commands/qa/index',
          },
          items: [
            {type: 'autogenerated', dirName: 'commands/qa'},
          ],
        },
        {
          type: 'category',
          label: 'OPS (30)',
          collapsed: true,
          link: {
            type: 'doc',
            id: 'commands/ops/index',
          },
          items: [
            {type: 'autogenerated', dirName: 'commands/ops'},
          ],
        },
        {
          type: 'category',
          label: 'DOC (9)',
          collapsed: true,
          link: {
            type: 'doc',
            id: 'commands/doc/index',
          },
          items: [
            {type: 'autogenerated', dirName: 'commands/doc'},
          ],
        },
        {
          type: 'category',
          label: 'BIZ (11)',
          collapsed: true,
          link: {
            type: 'doc',
            id: 'commands/biz/index',
          },
          items: [
            {type: 'autogenerated', dirName: 'commands/biz'},
          ],
        },
        {
          type: 'category',
          label: 'GROWTH (11)',
          collapsed: true,
          link: {
            type: 'doc',
            id: 'commands/growth/index',
          },
          items: [
            {type: 'autogenerated', dirName: 'commands/growth'},
          ],
        },
        {
          type: 'category',
          label: 'DATA (3)',
          collapsed: true,
          link: {
            type: 'doc',
            id: 'commands/data/index',
          },
          items: [
            {type: 'autogenerated', dirName: 'commands/data'},
          ],
        },
        {
          type: 'category',
          label: 'LEGAL (5)',
          collapsed: true,
          link: {
            type: 'doc',
            id: 'commands/legal/index',
          },
          items: [
            {type: 'autogenerated', dirName: 'commands/legal'},
          ],
        },
        {
          type: 'category',
          label: 'Orchestrateur (2)',
          collapsed: false,
          items: [
            'commands/other/assistant',
            'commands/other/assistant-auto',
          ],
        },
      ],
    },
  ],

  // Agents sidebar
  agentsSidebar: [
    {
      type: 'category',
      label: 'Agents',
      collapsed: false,
      link: {
        type: 'doc',
        id: 'agents/index',
      },
      items: [
        {type: 'autogenerated', dirName: 'agents'},
      ],
    },
  ],

  // Skills sidebar
  skillsSidebar: [
    {
      type: 'category',
      label: 'Skills',
      collapsed: false,
      link: {
        type: 'doc',
        id: 'skills/index',
      },
      items: [
        {type: 'autogenerated', dirName: 'skills'},
      ],
    },
  ],

  // Rules sidebar
  rulesSidebar: [
    {
      type: 'category',
      label: 'Rules',
      collapsed: false,
      link: {
        type: 'doc',
        id: 'rules/index',
      },
      items: [
        {type: 'autogenerated', dirName: 'rules'},
      ],
    },
  ],

  // Tutorials sidebar
  tutorialsSidebar: [
    {
      type: 'category',
      label: 'Tutoriels',
      collapsed: false,
      link: {
        type: 'doc',
        id: 'tutorials/index',
      },
      items: [
        'tutorials/premier-projet',
        'tutorials/feature-react',
        'tutorials/api-rest-node',
        'tutorials/flutter-supabase',
        'tutorials/audit-securite',
        'tutorials/cicd-github',
        'tutorials/refactoring-legacy',
        'tutorials/proxmox-infra',
        'tutorials/opnsense-firewall',
      ],
    },
  ],

  // Examples sidebar
  examplesSidebar: [
    {
      type: 'category',
      label: 'Exemples',
      collapsed: false,
      link: {
        type: 'doc',
        id: 'examples/index',
      },
      items: [
        {
          type: 'category',
          label: 'Web',
          collapsed: true,
          items: [
            'examples/web/react-component',
            'examples/web/react-hook',
            'examples/web/nextjs-api',
          ],
        },
        {
          type: 'category',
          label: 'Mobile',
          collapsed: true,
          items: [
            'examples/mobile/flutter-screen',
            'examples/mobile/flutter-bloc',
          ],
        },
        {
          type: 'category',
          label: 'API',
          collapsed: true,
          items: [
            'examples/api/rest-endpoint',
            'examples/api/graphql-resolver',
            'examples/api/trpc-procedure',
          ],
        },
        {
          type: 'category',
          label: 'Ops',
          collapsed: true,
          items: [
            'examples/ops/docker-setup',
            'examples/ops/ci-pipeline',
            'examples/ops/terraform-module',
            'examples/ops/proxmox-vm',
            'examples/ops/opnsense-config',
          ],
        },
      ],
    },
  ],

  // Guides sidebar
  guidesSidebar: [
    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      link: {
        type: 'doc',
        id: 'guides/index',
      },
      items: [
        'guides/web-development',
        'guides/mobile-development',
        'guides/api-development',
        'guides/data-engineering',
        'guides/startup',
        'guides/best-practices',
        'guides/faq',
        'guides/troubleshooting',
        'guides/migration',
      ],
    },
  ],

  // Reference sidebar
  referenceSidebar: [
    {
      type: 'category',
      label: 'Référence',
      collapsed: false,
      link: {
        type: 'doc',
        id: 'reference/index',
      },
      items: [
        'reference/commands-matrix',
        'reference/agents-matrix',
        'reference/scripts',
        'reference/cheatsheet',
      ],
    },
  ],
};

export default sidebars;
